language: java
sudo: false
script: ./gradlew -d clean build

jdk:
  - oraclejdk8

notifications:
  # Email notifications are disabled to not annoy anybody.
  # See http://about.travis-ci.org/docs/user/build-configuration/ to learn more
  # about configuring notification recipients and more.
  email: false